# Generated by Django 5.1.4 on 2025-03-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0003_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
